### ISSUE TITLE
constant names

### ISSUE THREAD

**Issue by pixelzoom** [heldentodd/xray-diffraction#19]
Related to #1 (code review).

> - [ ] Are there any constants that are duplicated in multiple files that should be factored out into a {{REPO}}Constants.js file?

There are a couple of constants that do not conform to the JavaScript naming conventions for constants. They should be uppercase, `SCALE_F`. 

```js
// CrystalNode.js
  const ScaleF = 8;

// XrayDiffractionScreenView.js
const scaleF = 8;
```

And if these are indeed the same `SCALE_F`, they should be moved to `XrayDiffractionConstants`.   A better name might also be in order, because I'm left wondering what "F" is.

**Comment by pixelzoom** [comment]
In Lattice.js, `const crystalSize` should be `const CRYSTAL_SIZE`.

**Comment by heldentodd** [comment]
ScaleF is a constant to transform the model to the view screen. Basically all sizes (in Angstrom in the model) get multiplied by 8 to make them look pretty on screen. I think I am in trouble here because I see some PhETs using something like a modelToView function. For now, I'm renaming it to SCALE_FACTOR and moving it to XrayDiffractionConstants.

crystalSize changed to CRYSTAL_SIZE.

**Comment by pixelzoom** [comment]
PhET's standard 2D model-view transform is phetcommon/js/ModelViewTransform2.js.   Let me know if you have any questions about it.  

And if your transform is simple enough that it's just a scale (like SCALE_FACTOR), that's acceptable too.   The important bit is that you understand that there's a transform, and you handle it consistently -- which you've done!

**Comment by heldentodd** [comment]
Thank you. It is nice to know that this tool is there for when I need a more powerful transformation tool. For now the simple scale factor works well.
